gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - gripper_right_joint
    - gripper_left_joint
  constraints:
      goal_time: 0.6
      max_effort: 100
      stopped_velocity_tolerance: 0.05
      gripper_right_joint: {trajectory: 0.1, goal: 0.1}
      gripper_left_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  50
  action_monitor_rate: 50
  gains:
    gripper_right_joint: {p: 1000,  d: 10, i: 0, i_clamp: 0}
    gripper_left_joint: {p: 1000,  d: 10, i: 0, i_clamp: 0}
