arm_controller:
   type: position_controllers/JointTrajectoryController
   joints:
     - shoulder_yaw_joint
     - shoulder_pitch_joint
     - elbow_pitch_joint
     - wrist_pitch_joint
     - wrist_roll_joint
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      shoulder_yaw_joint: {trajectory: 0.1, goal: 0.1}
      shoulder_pitch_joint: {trajectory: 0.1, goal: 0.1}
      elbow_pitch_joint: {trajectory: 0.1, goal: 0.1}
      wrist_pitch_joint: {trajectory: 0.1, goal: 0.1}
      wrist_roll_joint: {trajectory: 0.1, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate:  50
   action_monitor_rate: 50
   gains:
      shoulder_yaw_joint: {p: 100,  d: 0.1, i: 0, i_clamp: 0}
      shoulder_pitch_joint: {p: 100,  d: 0.1, i: 0, i_clamp: 0}
      elbow_pitch_joint: {p: 100,  d: 0.1, i: 0, i_clamp: 0}
      wrist_pitch_joint: {p: 100,  d: 0.1, i: 0, i_clamp: 0}
      wrist_roll_joint: {p: 100,  d: 0.1, i: 0, i_clamp: 0}
